<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="test1"
    errors="1" failures="0" hostname="" id="" package="test1" skipped="0"
    tests="1" time="0.07200" timestamp="Wed, 11 Jul 2018 21:30:03 GMT">
  
    <testcase name="WantedErrorMessages" classname="test1" time="0.07200" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Test1 / WantedErrorMessages]:

  ReferenceError: useXpath is not defined
    at Object.WantedErrorMessages (C:\Users\North\Documents\DevMountain\2.3 Project Enter Wanted\tests\test1.js:45:9)
    at Module.call (C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\North\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
